weights: yolov5s.pt
cfg: /home/ansh.arora/IIITA_Winter21/YOLOv5-CustomDataset/yolov5/models/yolov5s.yaml
data: /home/ansh.arora/IIITA_Winter21/YOLOv5-CustomDataset/yolov5/data/bdd100k.yaml
hyp: /home/ansh.arora/IIITA_Winter21/YOLOv5-CustomDataset/yolov5/data/hyps/hyp.scratch.yaml
epochs: 10
batch_size: 8
imgsz: 720
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 24
project: runs/train
name: yolo_road_det
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolo_road_det8
